Microsoft/mesos-jenkins

Mesos/cron-jobs/mesos-nightly-build.sh, Mesos/cron-jobs/verify-review-requests.sh, Mesos/start-windows-build.ps1, Mesos/utils/common.py, Spartan/cron-jobs/spartan-nightly-build.sh
This PR includes:
- Fix for an issue with the function 'get_review_ids' that should return the review ids to be applied for a particular review request. It was missing an extra check to verify if the review request is already submitted.
- Add `MESOS_JENKINS_BRANCH` extra parameter when triggering Jenkins jobs.
=> Fix for the get_review_ids function and Jenkins job extra parameter

Mesos/start-windows-build.ps1
Enable Java and OpenSSL when building Mesos, thus more mesos and libprocess unit tests will be run.
=> Enable Java and OpenSSL for Mesos

DCOS/utils/install-latest-stable-acs-engine.sh
Instead of building from scratch the ACS Engine everytime a new
stable tag is released, we now use the git download URLs to download
the new stable binaries.
=> Change how ACS Engine is updated

DCOS/acs-engine-dcos-deploy.sh, DCOS/spartan-agent-setup.ps1, DCOS/templates/windows-service.xml, Mesos/jenkins-jobs/mesos-build.ps1, Mesos/jenkins-jobs/mesos-nightly-build.ps1, Mesos/start-windows-build.ps1
This pull request includes:
- Add workaround to enable RS3
- Temporarily, SSL is enabled only for the Reviewbot patches
- Add environment variables for the WinSW XML template
- Add parameter to enabled SSL when building Mesos
- Add Mesos nightly build Jenkins job script
=> Disable SSL for the Mesos nightly builds and add RS3 DC/OS deployments support

DCOS/spartan-agent-setup.ps1
Due to the fact that Spartan addresses are not available right away,
we do a ping to each address to make sure that they are responsive.
=> Add ping to the Spartan addresses

Mesos/start-windows-build.ps1
We fixed this upstream in the Mesos build. `curl.exe` is now
appropriately placed next to `mesos-agent.exe` by CMake automatically.
=> Stop copying curl.exe manually

Mesos/README.md, Mesos/cron-jobs/trigger-nightly-build.sh, Mesos/start-windows-build.ps1
This pull request introduces the following updates:
- Add a timestamp log for the trigger-nightly-build.sh cron job
- Fix typo for the Mesos `stout-tests`. The `stout-tests` were incorrectly logged as `stdout-tests`
=> Fix typo for Mesos stdout-tests and add log timestamp

DCOS/jenkins-jobs/dcos-testing.sh
When trying to create the `$TEMP_LOGS_DIR`, the command fails
if the parent directory doesn't exit.
To fix this issue we added the `-p` parameter to the mkdir,
so that the parent directory gets created as well.
=> Fix error when starting dcos-testing job

DCOS/jenkins-jobs/dcos-testing.sh, Mesos/start-windows-build.ps1, Mesos/utils/common.py
- Add missing check for circular dependencies for the `verify-review-requests.py` python script
- Enable parallel cmake builds
- Update Jenkins console log file copy
=> Parallel cmake builds & other updates

Mesos/start-windows-build.ps1
Previously, Visual Studio 2017 was used only for the `master` branch.
=> Use Visual Studio 2017 even for "1.5.x" Mesos branch

DCOS/templates/acs-engine-hybrid.json, DCOS/templates/preprovision/extensions/preprovision-agent-linux-private/v1/preprovision-agent-linux-private.sh, DCOS/templates/preprovision/extensions/preprovision-agent-linux-public/v1/preprovision-agent-linux-public.sh, DCOS/templates/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows.ps1, DCOS/templates/preprovision/extensions/preprovision-master-linux/v1/preprovision-master-linux.sh
NOTE: Do not merge until some acs-engine changes go through. This expects acs-engine to have the ability to handle the preProvision extension.
=> Expanded E2E test to also test mesos authentication.

DCOS/acs-engine-dcos-deploy.sh, DCOS/dcos-testing.sh, DCOS/templates/acs-engine-hybrid.json, DCOS/templates/marathon-fetcher-http.json, DCOS/templates/marathon-fetcher-https.json, DCOS/templates/marathon-fetcher-local.json, DCOS/templates/marathon-iis.json, DCOS/utils/check-marathon-app-health.py, Mesos/start-windows-build.ps1, Spartan/start-windows-build.ps1, global-variables.ps1
This pull request adds the following updates:
- Fix DC/OS config set for releases older than 1.10
- Update the script to check app tasks health
- Update preprovision scripts rootURL to the CI's stable URL
- Fix `check_open_port` logic
- Run Spartan eunit tests before common tests
- Fix temporary directory cleanup for the Mesos `start-windows-build.ps1` script
- Use first master as a proxy node to check fetcher functionality
- Add e-mail notifications for Spartan nightly build
=> E2E test to verify Spartan on Windows and other updates

DCOS/acs-engine-dcos-deploy.sh, DCOS/dcos-testing.sh, DCOS/templates/marathon-fetcher-http.json, DCOS/templates/marathon-fetcher-https.json, DCOS/templates/marathon-fetcher-local.json, DCOS/templates/marathon-iis.json
- Use `customnat` Docker network and `MESOS_HTTP` health checks
- Change default `DCOS_WINDOWS_BOOTSTRAP_URL`
- Remove DC/OS client session only if `DCOS_CLUSTER_ID` is set
- Create `dcos-nodes.json` when initializing the testing env and not at the logs collection
- Remove `agent_` from the logs directory name
=> Use az CLI to find slaves addresses and enable MESOS_HTTP health checks

DCOS/dcos-testing.sh
- Check if `DOCKER_CONTAINER_ID` is empty when trying to verify the fetcher file checksum from inside the Docker container
- Remove `BUILD_ID` variable set
- Copy environment file when collecting logs
- Remove any function calls from `dcos-testing.sh` script. From now on, this is meant to be sourced by the Jenkins job build script
- Save `dcos-nodes.json` when collecting logs
- Copy `dockerd.log` if present on the system. In the CI, we use the updated service wrapper to capture the stdout and stderr from the Docker daemon
=> Various updates to the main `dcos-testing.sh` script

DCOS/dcos-testing.sh, Diagnostics/start-windows-build.ps1, Mesos/start-windows-build.ps1, Spartan/start-windows-build.ps1
This pull request adds the following updates:
- Build Mesos binaries using `Release`
- Move `$env:GOPATH` variable set from Diagnostics to `New-TestingEnvironment` function
- Remove `git.exe config` calls
- Fix for logs collection when doing e2e DC/OS testing
=> Build Mesos using Release target and other updates

DCOS/autoscale-testing/AutoScale.Tests.ps1, Diagnostics/start-windows-build.ps1, Metrics/start-windows-build.ps1
This is needed otherwise we'll get the following error:
```
The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete.
Specify the UseBasicParsing parameter and try again.
```
=> Add '-UseBasicParsing' parameter to 'Invoke-WebRequest' calls

Diagnostics/start-windows-build.ps1
From now on, this is dynamically generated during the setup.
These are the commits to the setup scripts with this change:
* https://github.com/dcos/dcos-windows/commit/340e0c3a5290db10b3480068d175db1e6889d4b0
* https://github.com/dcos/dcos-windows/commit/0c5cd34838eebd56874561bc1e0eb8d526eb4e88
=> Remove servicelist.txt file generation

DCOS/acs-engine-dcos-deploy.sh, DCOS/templates/acs-engine/testing/hybrid.json
This pull requests adds the following updates:
- Latest Windows Server public insider build is used for DC/OS e2e testing
- Add `1.11.0` to the last of valid DC/OS releases for `DCOS/acs-engine-dcos-deploy.sh` script
=> Use latest insider build for DC/OS e2e testing

Mesos/start-windows-build.ps1
Sometimes the log files upload fails with the reason "Cannot open file". This is an example of a failing job [here](https://mesos-jenkins.westus.cloudapp.azure.com/job/mesos-reviewbot-testing/1073/console).
To simply fix this, copy the build outputs to a temporary directory and SCP that directory instead.
=> Fix log files upload

Spartan/fixes.patch, Spartan/start-windows-build.ps1
Instead of building Spartan against a fork with fixes applied, we now apply those patches after cloning the upstream Spartan DC/OS repository.
NOTE: This PR will be reverted if these fixes will be included in the upstream repository already.
=> Apply fixes from local patch file

Mesos/start-windows-build.ps1
`mesos-master.exe` is not needed on the DC/OS Windows agent.
=> Exclude mesos-master.exe when packaging Mesos binaries

DCOS/dcos-testing.sh, DCOS/templates/marathon/private-iis.json
This commit adds a new e2e test for dcos marathon app.
It tries to deploy a marathon app using a private docker image and by passing the login credentials of the registry via the json app definition.
=> Add e2e test for deploying marathon app with private image

Net/start-windows-build.ps1
This patch adds the equivalent to the following make
targets:
make xref dialyzer cover edoc .
xref - https://www.rebar3.org/docs/commands#section-xref
dialyzer - https://www.rebar3.org/docs/commands#section-dialyzer
cover - https://www.rebar3.org/docs/commands#section-cover
edoc - https://www.rebar3.org/docs/commands#section-edoc
Signed-off-by: Alin Gabriel Serdean <aserdean@ovn.org>
=> Add more unit tests to dcos-net build

Mesos/utils/common.py, Mesos/utils/post-build-result.py, Mesos/utils/python_compatibility_utils.py, Mesos/utils/trigger-gearman-jobs.py, Mesos/utils/verify-review-requests.py
This patch adds a new file called "python_compatibility_utils.py"
which contains the imports and methods that work on both
Python 2 and 3. It exposes the same name for functions and modules,
making it easy to use in other parts of the code.
It also adds brackets to the message from print function as that
is mandatory in Python 3.
Adds __init__.py file to be able to import from current directory
without adding the current directory to system path.
=> Add Python 3 support for the python scripts

DCOS/regression-testing/src/script/disable_linux_agents_dcos_metrics.sh
instead of disabling dcos-checks-poststart, remove dcos-metrics section from the configuration file
=> do not disable dcos-checks-poststart when disabling dcos-metrics-agent

DCOS/dcos-testing.sh, DCOS/templates/marathon/fetcher-http.json, DCOS/templates/marathon/fetcher-https.json, DCOS/templates/marathon/fetcher-local.json, DCOS/templates/marathon/iis.json, DCOS/templates/marathon/private-iis.json, DCOS/templates/marathon/windows-app.json
* Use 1803 Docker images in all the marathon templates
* Do not disable `dcos-checks-poststart` when disabling `dcos-metrics`
* Fix `test_windows_agent_dcos_dns`
=> Updates for DC/OS e2e testing job

DCOS/dcos-testing.sh
This is not needed anymore when triggering the downstream job.
=> Remove STATUS from parameters file

Net/start-windows-build.ps1
After the Windows build server update, the Windows 10 SDK version installed on the servers is `10.0.17134.0`.
=> Fix dcos-net libsodium dependency build

DCOS/DCOSWindowsAgentSetup.ps1
This is just a wrapper over the main init script from
http://dcos-win.westus.cloudapp.azure.com/dcos-windows/stable/
It does a couple of additional steps required in the CI:
* Enable WinRM on the DC/OS Windows agents. This is going to be  used to execute remote calls from Linux
* Enable SMB firewall rule to allow logs collection through the default SMB share
* Enable Docker debug logging
=> Add DCOSWindowsAgentSetup.ps1 used in the CI

Metrics/config/dcos-metrics-config.yaml, Metrics/start-windows-build.ps1
This PR contains the first of the two steps for addressing the following issue:
Adding the config file into the metrics.xip file
https://github.com/dcos/dcos-windows/issues/71
There will be a separate PR for dcos-windows repro for using this new config file in the metrics service.
=> Added config file for the Windows Metrics Service

Mesos/start-windows-build.ps1
Hi @ionutbalutoiu!
The new Python 3 versions of all the scripts are now upstream, at `support/python3/<name-of-script>`. I tried updating this, but didn't quite see how I make sure `C:\Program Files\Python36\python.exe` was in the path. I found:
```
Jenkins/set-up-windows-jenkins-build-server.ps1
29:    "python36" = @{
283:function Install-Python36 {
284:    $installDir = Join-Path $env:ProgramFiles "Python36"
285:    Install-CITool -InstallerPath $PACKAGES["python36"]["local_file"] `
445:    Install-Python36
```
But that didn't help me much. Would you be able to make the correct changes to use Python 3 with this special copy of the script? Thanks :)
=> WIP: Use Python 3 version of `apply-reviews.py` script.

DCOS/regression-testing/src/iis-rs3-marathon-template.json, DCOS/regression-testing/src/iis-rs4-marathon-template.json
This is just a sync with the latest updates to the DC/OS Windows setup scripts: https://github.com/dcos/dcos-windows/pull/84
=> Updated Marathon templates for the regression-testing

AgentBlob/GenerateAgentBlob.ps1, AgentBlob/PublishTestingAgentBlob.ps1
Get the CI `DCOSWindowsAgentSetup.ps1` script before publishing testing artifacts.
=> Fetch the CI DCOSWindowsAgentSetup.ps1 script

AgentBlob/GenerateAgentBlob.ps1, AgentBlob/PublishTestingAgentBlob.ps1
* Add `-q` parameter when using `git clone` 
* Add the `NewLatestSymlink` switch flag used to update the latest symlink for the Windows agent blob
=> Update `GenerateAgentBlob.ps1` and `PublishTestingAgentBlob.ps1`

DCOS/start-dcos-e2e-testing.sh
Source `dcos-testing.sh` earlier to have `check_exit_code` available when updating `acs-engine`.
=> Fix DCOS/start-dcos-e2e-testing.sh

AgentBlob/GenerateAgentBlob.ps1, AgentBlob/PublishTestingAgentBlob.ps1
This commit adds the following updates:
* Move the fetching of the `DCOSWindowsAgentSetup.ps1` and the pre-provision scripts from `PublishTestingAgentBlob.ps1` to `GenerateAgentBlob.ps1`
* Instead of individually downloading the `DCOSWindowsAgentSetup.ps1` script, we copy it from the local cloned `dcos/dcos-windows` repository
* Copy the `DCOSWindowsAgentSetup.ps1` from its new location in the `dcos/dcos-windows` repository. For now, there is a check that will copy from the old location, to maintain backwards compatibility
=> Move CI init scripts fetch

DCOS/dcos-testing.sh, DCOS/start-dcos-e2e-testing.sh
This pull request addresses the issue of opening the DC/OS port 80 to the internet. This is a security concern. From now on, we must set a list of allowed IP addresses to restrict access to the testing clusters.
Add `MASTER_WHITELISTED_IPS` environment variable, a list of space-separated list of IPs, allowed to use DC/OS port 80.
=> Add Whitelisted IPs to Master NSG

AgentBlob/GenerateAgentBlob.ps1
Use `Copy-Item` instead of `Move-Item`.
Otherwise, the following code fails: https://github.com/Microsoft/mesos-jenkins/blob/6cb6b8e4fd134d22da75a3094aaec9c8a2fac54c/AgentBlob/GenerateAgentBlob.ps1#L130-L133
Using `Move-Item` will cause all the other lines of code to fail, if they try to copy from the previous location.
=> Fix AgentBlob/GenerateAgentBlob.ps1

DCOS/utils/check-marathon-app-health.py
Added --ignore-last-task-failure flag to check-marathon-app-health.py, which is needed for shutdown tests, so that the script reports the app as healthy, even if the task was respawned on another node.
=> Added --ignore-last-task-failure flag to check-marathon-app-health.py

Mesos/start-windows-build.ps1
@ionutbalutoiu This switches us to the native threading library which unblocks a myriad of tests, and should be the default. We'll eventually remove libevent support from Windows (probably after adding SSL support on top of libwinio).
Question 1: Do the Jenkins builds set `EnableSSL` to true? If so, we should disable that.
Question 2: Is this the only thing we need to change for the bits that DC/OS cluters pick up, or is there another build?
=> Use libwinio instead of libevent unless SSL is enabled

DCOS/preprovision/extensions/preprovision-agent-linux-private/v1/preprovision-agent-linux-private.sh, DCOS/preprovision/extensions/preprovision-agent-linux-public/v1/preprovision-agent-linux-public.sh
The `dcos-checks-poststart` started using `dcos-check-runner` instead
of `dcos-diagnostics` since https://github.com/dcos/dcos/commit/dfdb6e436fe1f509eb845b153b30f1728a41c9ab.
This means that the `dcos-checks-poststart` systemd service uses
another configuration file for the checks. Instead of
`dcos-diagnostics-runner-config.json`, the new configuration file
is `dcos-check-config.json`.
The current dcos-engine Linux pre-provision scripts won't have
Linux healthy nodes with Mesos auth enabled, unless the new
config file is updated by removing the `mesos_agent_registered_with_masters`
check.
For a better flexibility, this commit removes the check via
a Python script, instead of fetching an already edited config file.
=> Fix Linux agents pre-provision scripts

DCOS/dcos-testing.sh, DCOS/utils/start-mesos-service.ps1, DCOS/utils/stop-mesos-service.ps1
We deploy a test application, stop the service on the windows agent that's running the task, then we wait for the task to migrate to another node (there must be at least two nodes with the same role for this) and check its health. If the task migration was successful, we start the mesos slave service back up on the initial node.
=> Add graceful shutdown test for windows agents

Mesos/start-windows-build.ps1
Fix syntax error for the script `Mesos/start-windows-build.ps1`. This solves the following error in the CI:
```
At C:\Jenkins\workspace\mesos-reviewbot-testing\Mesos\start-windows-build.ps1:158 char:51
+             $parameters += "-DENABLE_LIBWINIO=ON",
+                                                   ~
Missing expression after ','.
At C:\Jenkins\workspace\mesos-reviewbot-testing\Mesos\start-windows-build.ps1:155 char:28
+             $parameters += "-DENABLE_LIBEVENT=ON",
+                            ~~~~~~~~~~~~~~~~~~~~~~~
The assignment expression is not valid. The input to an assignment operator must be an object that is able to accept 
assignments, such as a variable or a property.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ …
```
=> Fix syntax error

DCOS/dcos-testing.sh, DCOS/utils/kill-mesos-agent-ungraceful.ps1
We deploy a test application, kill the agent, disable recovery options, and wait for the task to migrate to a new host.
=> Add ungraceful shutdown test for windows agents

DCOS/dcos-testing.sh
Added a fix for checking that the new task host is not null. This happens because the DCOS API sometimes takes 2-3 seconds to report a task host change, even if the task is up & running & healthy.
Also added $WORKSPACE to chmod +x path.
=> Fix for null variable

DCOS/dcos-testing.sh
Add fix for checking that the new task host is not null in the graceful shutdown test. This happens because the DCOS API sometimes takes 2-3 seconds to report a task host change, even if the task is up & running & healthy.
=> Fix for null variable in graceful shutdown test

AgentBlob/GenerateAgentBlob.ps1
Update the default value for the `$DockerBinariesBaseUrl` used in the `AgentBlob/GenerateAgentBlob.ps1` PowerShell script.
=> Bump Docker to latest EE release

DCOS/utils/utils.sh
The `nc` command sometimes never finishes if the port is not open, thus making the Jenkins jobs to be stucked.
When checking if the port is open via `nc`, we let a timeout of 5 seconds.
=> Add timeout nc cmd

Modules/CIUtils/CIUtils.psm1
This parameter is added to `Start-Process` PowerShell cmdlet used to invoke `curl.exe` requests.
=> Add '-NoNewWindow' parameter

DCOS/autoscale-testing/AutoScale.Tests.ps1
We might not have the current logged session as the proper one.
Therefore, we disconnect any session and we connect the appropriate Azure account.
=> Scaling tests update: Disconnect any logged account

DCOS/dcos-engine-deploy.sh
Update the default value used for the DC/OS Linux bootstrap URL.
From now on, this points to the `dcos_generate_config.sh` given by the Mesosphere DC/OS nightly builds from https://github.com/dcos/dcos/pull/2481.
=> Update Linux DC/OS bootstrap URL

DCOS/utils/kill-mesos-agent-ungraceful.ps1, DCOS/utils/kill-mesos-agent.ps1, DCOS/utils/start-mesos-service.ps1, DCOS/utils/stop-mesos-service.ps1
Add detection of service name for private/public windows agents in Powershell scripts, since the naming for the windows service has changed, now being dcos-mesos-slave for private agents and dcos-mesos-slave public for public agents.
=> Add detection of service name for private/public windows agents

Jenkins/set-up-windows-jenkins-build-server.ps1
This is required when dealing with repos with symlinks (like the upsteam [dcos/dcos](https://github.com/dcos/dcos) repository).
=> Enable core.symlinks system-wide Git config

global-variables.ps1
The old version returns `301 Moved Permanently` causing some PowerShell code to fail.
=> Bump 7-Zip URL

Mesos/start-windows-build.ps1
The Mesos reviewbot uses a python script to post results to Reviewboard, and for now it can deal only with uft-8 encoded log files.
Signed-off-by: Ionut Balutoiu <ibalutoiu@cloudbasesolutions.com>
Co-authored-by: Alin Gabriel Serdean <aserdean@cloudbasesolutions.com>
Co-authored-by: Mihai Gheorghe <mgheorghe@cloudbasesolutions.com>
=> Save logs with uft8 encoding

Diagnostics/start-windows-build.ps1, Mesos/start-windows-build.ps1, Metrics/start-windows-build.ps1, Net/start-windows-build.ps1
To avoid confusion and simply debugging in case of job failures, the log files are not merged into a single one, instead of separate files for stdout and stderr streams.
=> Use single log file

DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows.ps1
We run Docker pull against all the used images in the CI. This action will update the local images if they are outdated. Having a Docker image rm for all the cached images is useless in this scenario.
=> Remove useless Docker image rm

Mesos/utils/post-build-result.py
Doing `response.read()` twice results into an empty value for str representation of the log, since there isn't anything left to ready from the `response` variable.
This commit fixes this issue by calling `response.read()` only once.
=> Fix post-build-result.py

Net/start-windows-build.ps1
The logging wasn't using the log file URL for the executed process, but the base URL with all the logs.
This commit fixes this.
=> Fix URL used for log file

DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows.ps1
This way, we can use `$LASTEXITCODE` for error checking in other scripts that call this `preprovision-agent-windows.ps1`.
=> Exit with 1 instead of re-throwing exception

DCOS/utils/kill-mesos-agent-ungraceful.ps1, DCOS/utils/kill-mesos-agent.ps1, DCOS/utils/start-mesos-service.ps1, DCOS/utils/stop-mesos-service.ps1
By default, WaitForStatus($status, '00:00:30') actually does a delta from 12AM, instead of a 30s time, so you end up waiting for hours. We fix this by creating a new TimeSpan object that is actually 30 seconds long, and 60 seconds where appropriate.
=> Fix WaitForStatus bug with new TimeSpan object

Mesos/start-windows-build.ps1
Since https://reviews.apache.org/r/68619, the Python3 scripts are the default ones.
=> Change Python support scripts paths

DCOS/dcos-engine-deploy.sh
The DC/OS Linux builds will be published to this location from now on.
=> Update the default value for DCOS_BOOTSTRAP_URL

DCOS/preprovision/extensions/preprovision-agent-linux-private/v1/preprovision-agent-linux-private.sh, DCOS/preprovision/extensions/preprovision-agent-linux-public/v1/preprovision-agent-linux-public.sh, DCOS/preprovision/extensions/preprovision-master-linux/v1/preprovision-master-linux.sh
A recent commit into DC/OS master branch (https://github.com/dcos/dcos/commit/c140fc7702be9edcbff420e7d29ae9e4237d5c2b) introduces some `ExecStartPre=` systemd exec calls that are expecting `chmod` and `chown` to be present into `/usr/bin/` directory.
=> Fix Linux nodes health issues

Net/start-windows-build.ps1
* Add `windows` to the target, in order to avoid any build errors on Windows when running the dcos-net unit tests
* Add `-v` parameter for more verbose logs
=> Fix Net/start-windows-build.ps1

DCOS/fluentd-testing/fluentd.Tests.ps1
For the test case with Fluentd service restart, allow a timeout of 1 minute.
=> Allow a timeout of 1 minute after service restart

DCOS/provision/extensions/preprovision-agent-linux-private/v1/preprovision-agent-linux-private-win-bootstrap-node.sh, DCOS/provision/extensions/preprovision-agent-linux-private/v1/preprovision-agent-linux-private.sh, DCOS/provision/extensions/preprovision-agent-linux-public/v1/preprovision-agent-linux-public-win-bootstrap-node.sh, DCOS/provision/extensions/preprovision-agent-linux-public/v1/preprovision-agent-linux-public.sh, DCOS/scalability-testing/Scalability.Tests.ps1, DCOS/templates/dcos-engine/hybrid-win-bootstrap-node.json
* Allow a timeout for health checks post scale up/down scenarios
* Cleanup Linux preprovision scripts
* Fix hybrid-win-bootstrap-node.json pre-provision scripts
=> Updates for DC/OS e2e testing with Windows bootstrap node

DCOS/provision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows-win-bootstrap-node.ps1, DCOS/provision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows.ps1
The Mesos environment file passed to the service wrapper must have the system's default encoding.
=> Fix Mesos env file encoding

DCOS/templates/dcos-engine/hybrid-win-bootstrap-node.json
Use the latest Docker EE version into testing DC/OS Windows clusters.
=> Bump Docker version

DCOS/provision/extensions/postinstall-agent-windows/v1/postinstall-agent-windows.ps1
The dcos-metrics agent is constantly flipping between stopped / running
when Mesos auth is enabled.
Sometimes, the Stop-Service will fail if the service is stopped
into a flipping state even though the service is successfully stopped.
Adding a retry will solve this.
=> Add retry to dcos-metrics Stop-Service

DCOS/Jenkinsfile
These are testing DC/OS deployments without Pkgpanda that are removed from dcos-engine.
=> Remove e2e and buildBlob from Jenkinsfile

DCOS/dcos-engine-deploy.sh, DCOS/dcos-testing.sh, DCOS/templates/dcos-engine/hybrid-win-bootstrap-node.json
- This PR adds a test case for the `dcos-engine upgrade` command: we upgrade the cluster from the stable Windows bootstrap URL to the testing Windows bootstrap URL, but we keep the same DC/OS version.
=> Add test case for DC/OS upgrade.

DCOS/dcos-testing.sh
- This PR fixes an issue with dcos-engine login by changing the auth method to `client_secret` from the default `device`.
=> Fix dcos-engine upgrade login.

Jenkins/set-up-windows-jenkins-build-server.ps1
Install gcc on Jenkins slave , required with go 1.11
=> Install gcc on Jenkins slave

Diagnostics/start-windows-build.ps1, Metrics/start-windows-build.ps1
Tests that are started with powershell and fail do not throw errors.
This PR fixes this issue
metrics-testing FAILURE will be resolved after the following is merged:
https://github.com/dcos/dcos-metrics/pull/166
=> Fix LASTEXITCODES for powershell scripts

DCOS/utils/collect-windows-machine-logs.sh
Add check for crash dumps on the windows client collect logs.
If crash dumps are found in the their respective directories, a warning is raised and they are collected
=> Add check for crash dumps on the windows client collect logs

DCOS/templates/dcos-engine/hybrid.json
Docker released enterprise version 4 for the `18.03.1`. This pull request explicitly set this version into DC/OS e2e testing clusters.
=> Bump Docker to 18.03.1-ee-4

DCOS/utils/check-marathon-app-health.py
Recently, there are a lot of these Docker transient errors when spawning
the first task:
```
Failed to run docker container: User defined networks require Docker version 1.9.0 or higher
```
This is not consistent and it's happening only when trying to spawn
the first task, while second one will work.
=> Ignore failed tasks by default
