Microsoft/mesos-jenkins

DCOS/README.md
Mesos/start-windows-build.ps1
Mesos/utils/common.py
Mesos/utils/get-review-ids.py

This pull request includes:
- Fix for the get_review_ids function that was causing failures when applying patches from Reviewboard
- Mesos unit test `MasterAPITest.EventAuthorizationFiltering` is enabled again since the known issue was fixed
- Updated DCOS README

Fixes and removed disabled Mesos unit tests

---

DCOS/jenkins-jobs/dcos-testing.sh
DCOS/templates/acs-engine-hybrid.json
DCOS/templates/acs-engine-simple.json
DCOS/utils/check-custom-attributes.py
DCOS/utils/common.py
DCOS/utils/dcos-node-addresses.py
DCOS/utils/install-latest-stable-acs-engine.sh

- Fix `install-latest-stable-acs-engine.sh` script used to fetch the released `acs-engine`
- Add additional custom attribute to the Mesos slaves and validate that from the `dcos-testing` main job

Update dcos-testing main job script and other fixes

---

Mesos/utils/post-build-result.py
Mesos/utils/verify-review-requests.py

- Small code cleanup: Remove useless try / catch block
- Remove check for the reviewers: From now on, the CI will be triggered even for the patches that do not have yet a reviewer added to them

Code cleanup and remove check for the reviewers

---

DCOS/jenkins-jobs/dcos-testing.sh

This pull request adds the following updates:
- Copy logs only if the logs directory exist
- Remove logs collecting if the DCOS API port is not succesfully opened

Fixes for logs gathering

---

DCOS/jenkins-jobs/dcos-testing.sh
DCOS/utils/check-custom-attributes.py
DCOS/utils/check-marathon-app-health.py
DCOS/utils/utils.sh
README.md

This pull request adds the following updates:
- Update README
- Set the `dcos-testing` Jenkins job `BUILD_ID` variable to something more unique based on the current date
- Update `check-custom-attributes.py`: Make the script exit with code different than zero instead of just printing 'True' or 'False' when verifying if the custom attributes are set
- Update `dcos-testing` Jenkins job script: Use better error handling and code cleanup

Better error handling for the dcos-testing job & other updates

---

Mesos/start-windows-build.ps1
Spartan/start-windows-build.ps1
global-variables.ps1

The SSH key private file is injected via Jenkins credentials from now on.

Remove hard-coded SSH key path

---

DCOS/acs-engine-dcos-deploy.sh

The validation is done via `az` tool.

Validate ARM templates before deploying them

---

Diagnostics/README.md
Diagnostics/config/dcos-diagnostics-config.json
Diagnostics/config/dcos-diagnostics-endpoint-config.json
Diagnostics/config/dcos-diagnostics-runner-config.json
Diagnostics/start-windows-build.ps1
global-variables.ps1

This PR contains changes needed for producing diagnostics.zip 
Note: the remote uploading part is not done yet.

Added build scripts for the dcos-diagnostics binaries

---

Diagnostics/README.md
Diagnostics/start-windows-build.ps1

This PR addressed the remaining review feedbacks from Ionut's last round of  review.

Addressed a few minor issuse in Diagnostics script and readme

---

DCOS/dcos-testing.sh

Enable logs collection for DC/OS diagnostics.

Collect logs for DC/OS diagnostics as well

---

DCOS/autoscale-testing/AutoScale.Tests.ps1

A new test, AreAllNodesHealthy, was added to the existing scaler unitests for validating the agent nodes healthy in the following cases:
1. Initial cluster deployment
2. after cluster scale-up operation
3. after cluster scale-down operation
Note: This PR along with the follow two PRs need to be merged for the same deployment to avoid test failures.
https://github.com/Microsoft/mesos-jenkins/pull/37
https://github.com/dcos/dcos-windows/pull/24

Added end-to-end test cases for checking the healthy states of all agent nodes

---

DCOS/autoscale-testing/AutoScale.Tests.ps1
Metrics/README.md
Metrics/start-windows-build.ps1
global-variables.ps1

@soccerGB
Added build scripts for the dcos-metrics service

Added build scripts for the dcos-metrics service

---

Metrics/start-windows-build.ps1
global-variables.ps1

This pull request fixes the DC/OS Metrics build PowerShell script from CI.

Fix DC/OS Metrics build script

---

Net/README.md
Net/start-windows-build.ps1
global-variables.ps1

This pull request adds the build script for `dcos-net` on Windows

Add dcos-net build script

---

Jenkins/set-up-windows-jenkins-build-server.ps1
README.md

* Update main repository `README`
* Add PowerShell script to be used when setting up a new Windows Jenkins slave

Add PowerShell script to set up a Jenkins Windows build server & README update

---

Mesos/utils/common.py
Mesos/utils/verify-review-requests.py

The query parameter has now been replaced to expect a string in JSON
format.
It now checks all the patches from the last 8 hours by default.
Instead of querying using "to-groups" now it uses the repository ID.

Improve script logic to detect if a change needs verification

---

DCOS/regression-testing/cluster-defs/lnx/dcos-m3.l2-2.bstrap.vnet.json
DCOS/regression-testing/cluster-defs/lnx/dcos-m3.l2-2.vnet.json

regression tests: adjust VM size to be supported by the region

adjust VM size for the region

---

DCOS/dcos-testing.sh
global-variables.ps1

This makes the scripts a little bit cleaner.

Remove hard-coded IPs for Jenkins and log server

---

Diagnostics/README.md
Mesos/README.md
Metrics/README.md

Gearman is not used anymore with Jenkins.

Remove Gearman reference from all the README

---

DCOS/templates/acs-engine/stable/hybrid.json
DCOS/templates/acs-engine/stable/simple.json
DCOS/templates/acs-engine/testing/hybrid.json
DCOS/templates/acs-engine/testing/simple.json

* Fix `osType`
* Use official 1803 Azure images

Fix osType and use official 1803 Azure images

---

DCOS/dcos-testing.sh

Having the output discarded, we might encounter issues when a command fails and perhaps the output had some useful information for debugging.

Remove output discard from various commands

---

Jenkins/set-up-windows-jenkins-build-server.ps1

Bump Python version used and add `TODO`'s for the remaining items.

Update set-up-windows-jenkins-build-server.ps1 script

---

DCOS/utils/utils.sh

* Add local to the variables from `run_ssh_command`, `download_files_via_scp` and `upload_files_via_scp`
* Use `return 1` instead of `exit 1` in functions

Fix DC/OS utils.sh functions

---

DCOS/templates/preprovision/extensions/preprovision-agent-linux-private/v1/preprovision-agent-linux-private.sh
DCOS/templates/preprovision/extensions/preprovision-agent-linux-public/v1/preprovision-agent-linux-public.sh

added post-install script to Linux preprovision

added post-install script to Linux preprovision

---

DCOS/DCOSWindowsAgentSetup.ps1

added logs with timestamps to DCOSWindowsAgentSetup.ps1

added logs to DCOSWindowsAgentSetup.ps1

---

DCOS/templates/marathon/fetcher-http.json
DCOS/templates/marathon/fetcher-https.json
DCOS/templates/marathon/fetcher-local.json
DCOS/templates/marathon/iis.json
DCOS/templates/marathon/private-iis.json
DCOS/templates/marathon/windows-app.json

This is just a sync with the latest PR from dcos/dcos-windows:
https://github.com/dcos/dcos-windows/pull/84

Update DC/OS network used in the Marathon templates

---

AgentBlob/GenerateAgentBlob.ps1

Ionut, here is the script for generating WindowsAgentBlob.zip and 7Zip installer.

Added a script for generating WindowsAgentBlob and 7Zip Installer

---

Jenkins/set-up-windows-jenkins-build-server.ps1

Small update the `Jenkins/set-up-windows-jenkins-build-server.ps1` PowerShell script.

Bump Docker version used for the Jenkins slave setup script

---

DCOS/dcos-testing.sh

Fix log messages when checking if a port is open

Fix log messages in dcos-testing.sh

---

DCOS/DCOSWindowsAgentSetup.ps1

Add missing `Add-ToSystemPath` function

Fix `DCOS/DCOSWindowsAgentSetup.ps1`

---

AgentBlob/GenerateAgentBlob.ps1
AgentBlob/PublishTestingAgentBlob.ps1

* Use `Start-FileDownload` utils function in `AgentBlob\GenerateAgentBlob.ps1`
* Use global variable for the setup scripts Git repo URL
* Copy the preprovision scripts before publishing the Windows agent blob

Update GenerateAgentBlob.ps1 and PublishTestingAgentBlob.ps1

---

DCOS/utils/wsmancmd.py

Add wsmancmd.py --file support for powershell scripts (doesn't support comments in the PS scripts right now) and update the wsmancmd linux binary.

Add wsmancmd --file support 

---

.gitattributes
Jenkins/set-up-windows-jenkins-build-server.ps1

* Add `.gitattributes`
* Revert commit https://github.com/Microsoft/mesos-jenkins/commit/215d5199b15f4eecd20c276a01a15fd373a1ef16 and set `core.autocrlf` to `true`

Revert git `core.autocrlf false` and add .gitattributes

---

AgentBlob/GenerateAgentBlob.ps1

This fixes a wrong call to the artifacts directory variable.

Fix AgentBlob/GenerateAgentBlob.ps1

---

DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows-ci-setup.ps1
DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows-fluentd.ps1
DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows.ps1
Modules/CIUtils/CIUtils.psm1

Use `curl.exe` instead of `Invoke-WebRequest`.
Fixes issue: https://github.com/Microsoft/mesos-jenkins/issues/158

Improve pre-provision scripts execution time

---

DCOS/preprovision/extensions/preprovision-agent-linux-private/v1/preprovision-agent-linux-private.sh
DCOS/preprovision/extensions/preprovision-agent-linux-public/v1/preprovision-agent-linux-public.sh

* Re-add `dcos-diagnostics-runner-config.json` config update
* Update `dcos-check-config.json` only if file exists

Backward compatibility updates

---

DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows-ci-setup.ps1

Simplify the `Start-FileDownload` function from the pre-provision PowerShell script.
The old implementation had a bug and some files were never downloaded.
Error given when it was trying to download the `service-wrapper.exe`:
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: timeout Will retry in 1 seconds. 30 retries left.
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: timeout Will retry in 2 seconds. 29 retries left.
```

Fix preprovision-agent-windows-ci-setup.ps1

---

Diagnostics/start-windows-build.ps1

Append $GOPATH\bin to PATH
This is needed for the Diagnostics build script

Append GOPATH\bin to PATH

---

DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows-ci-setup.ps1
DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows.ps1

* Fix `preprovision-agent-windows-ci-setup.ps1` log message
* Pre-pull `dcoswindowsci/windows:1803` testing image

Pre-pull CI testing Docker image and fix log message

---

DCOS/dcos-testing.sh
DCOS/templates/marathon/iis.json

* Re-add `test_iis` functional test
* Fix some comments and log messages

Re-add `test_iis` and fix comments / log messages

---

DCOS/Jenkinsfile

Add Jenkinsfile for mesos-jenkins PR tests

Add Jenkinsfile

---

DCOS/dcos-testing.sh

Add resilience testing for windows agents by spawning and killing tasks for each node, then checking to see if the recovered tasks are healthy.

Add resilience testing for windows agents

---

DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows-ci-setup.ps1

* Remove all the cached Docker images
* Pre-pull all the latest public Docker images

Update pre-provision CI script

---

AgentBlob/PublishStableAgentBlob.ps1

This PowerShell script will upload the latest testing Windows agent blob to the storage account used the production Azure CDN endpoint.

Add AgentBlob/PublishStableAgentBlob.ps1

---

Modules/CIUtils/CIUtils.psm1

The `--retry` parameter from `curl` works only when the initial connection is not successfully established.
If the connection drops during a file download with `curl`, the retry logic is not executed.
This commit drops the `--retry` parameter from `curl`, and adds the `Start-ExecuteWithRetry` wrapper over the `curl` exec call.

Fix Start-FileDownload retry logic

---

DCOS/utils/utils.sh

When the transient networking issues occur, sometimes the SSH and SCP commands are simply hanging indefinitely.
This commit adds a timeout over the SSH and SCP calls, in order to kill the processes if they are hanging.

Add timeout to the SSH and SCP commands

---

DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows-mesos-credentials.ps1

This new preprovision script change needs to be updated on the web server that hosts these example scripts.

Changed environment file location for the windows preprovision script.

---

DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows.ps1

Write the Mesos secret files with the proper encoding.

Fix pre-provision script

---

Jenkins/ci-image-Dockerfile
Jenkins/update_ci_win_docker_image.ps1

This pull request adds a PowerShell script to update the currently used CI Docker image.

Add PowerShell script to update CI Docker img

---

DCOS/dcos-testing.sh

* Remove extra spaces
* Add variable for timeout

Small code clean-up

---

Mesos/start-windows-build.ps1

* Save logs to a single file
* Fix typo

Update Mesos testing PowerShell script

---

Jenkins/set-up-windows-jenkins-build-server.ps1
Mesos/utils/post-build-result.py

Decode the log file using the proper encoding instead of using the default system encoding all the time.

Determine file encoding type

---

AgentBlob/GenerateAgentBlob.ps1
DCOS/Jenkinsfile
DCOS/utils/common.py
Diagnostics/start-windows-build.ps1
Mesos/start-windows-build.ps1
Metrics/start-windows-build.ps1
Net/start-windows-build.ps1

* Fix linux_slave_addresses functions
* Remove Branch and CommitId from remote_path functions
* Remove duplicate scripts dir from WindowsBlob
* Remove DCOS_BOOTSTRAP_URL environment variable
* End to end Test with binaries generated by current PR scripts.

E2E testing with binaries generated from PR

---

DCOS/dcos-engine-deploy.sh

This will point to the latest succesful build made by our internal Jenkins CI system.

Change default Linux DC/OS bootstrap URL

---

DCOS/Jenkinsfile

It is cleaner to inject this variable via Jenkins directly.

Remove MASTER_WHITELISTED_IPS

---

DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows.ps1
DCOS/start-dcos-e2e-testing.sh
DCOS/templates/dcos-engine/testing/hybrid.json

* Adapt pre-provision scripts
* Update `rootURL` for pre-provision scripts
* Update `DCOS_ENGINE_URL` fetch to do the testing

DC/OS e2e testing pipeline with Windows bootstrap node

---

DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows.ps1

Register Fluentd Windows service only if it doesn't exist.

Fix Windows pre-provision script

---

Jenkins/set-up-windows-jenkins-build-server.ps1

Use official Microsoft Docker installation via `Install-Package` PowerShell cmdlet.

Update Install-Docker function

---

AgentBlob/GenerateAgentBlob.ps1
DCOS/Jenkinsfile
DCOS/README.md
DCOS/dcos-engine-deploy.sh
DCOS/dcos-testing.sh
DCOS/preprovision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows.ps1
DCOS/start-dcos-e2e-testing.sh
DCOS/templates/marathon/fetcher-http.json
Jenkins/set-up-windows-jenkins-build-server.ps1
global-variables.ps1

The Azure resource group for the Jenkins CI has been moved to another subscription and the storage address changed.

Update storage server address

---

Jenkins/set-up-windows-jenkins-build-server.ps1

Bump the Erlang dependency used to build `dcos-net` for the Jenkins testing job.

Bump Erlang to OTP 21.0.1

---

DCOS/utils/collect-windows-machine-logs.sh

THe log file for Docker daemon was not correctly collected.

Fix collect-windows-machine-logs.sh

---

DCOS/provision/extensions/postinstall-agent-windows/v1/postinstall-agent-windows.ps1
DCOS/provision/extensions/preprovision-agent-windows/v1/preprovision-agent-windows-win-bootstrap-node.ps1

* Enable Windows Error Reporting (WER)
* Setup Docker with service wrapper in the post-install hook

Add WER and move code from pre-provision script to post-install script

---

DCOS/dcos-testing.sh

Sometimes the `compare_azure_vms_and_dcos_agents` function in `dcos-testing.sh` would fail simply because the DCOS API wasn't getting updated fast enough, so this PR adds 20 retries to that function, with a 10 second sleep time in between.

Add retries to compare_azure_vms_and_dcos_agents.

---

DCOS/dcos-testing.sh

Enable more test cases for the deployments with Windows bootstrap node and Pkgpanda setup on Windows.

Enable more test cases e2e Win bootstrap node

---

Diagnostics/start-windows-build.ps1
Mesos/start-windows-build.ps1
Metrics/start-windows-build.ps1
Net/start-windows-build.ps1

Set the custom build info to be used when doing a DC/OS build.

Set custom build info

---

Jenkins/set-up-windows-jenkins-build-server.ps1

Update Jenkins slave golang version to 1.11

Update Jenkins slave golang version to 1.11

---

Jenkins/set-up-windows-jenkins-build-server.ps1

Add error check for install gcc

Add error check for install gcc

---

Jenkins/set-up-windows-jenkins-build-server.ps1

Change msys2 install directory to c:\

Change msys2 install directory

---

DCOS/provision/extensions/postinstall-agent-windows/v1/postinstall-agent-windows.ps1

The dcos-metrics service was replaced by dcos-telegraf.

Remove dcos-metrics disable
